# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Asyl Hawa
description: asylhawa.com
email: HawaA@cardiff.ac.uk
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.asylhawa.com" # the base hostname & protocol for your site
twitter_username: asylhawa
github_username:  asyllh
keybase_username: asylhawa
mail_username:    HawaA@cardiff.ac.uk
paginate: 5

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
